
spring:
  application:
    name: configserver
  profiles:
    active: git
  #    active: native
    # we use native just for class path and file system location
    #whenever we use a class path to store our configuration files
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HamedMiri72/bank-config.git
          default-label: main
          timeout: 5
          #should only wait for 5 secend after thatthrow an error
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D://banck-config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


encrypt:
  key: "34g5645fdgd44353@/sdjfw387429"


server:
  port: 8071


