services:
#    accountsdb:
#      image: mysql
#      container_name: accountsdb
#      ports:
#        - "3305:3306"
#      healthcheck:
#        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#        interval: 10s
#        timeout: 10s
#        retries: 10
#        start_period: 10s
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: accountsdb
#      networks:
#        - bank-microservice
#
#    cardsdb:
#      image: mysql
#      container_name: cardsdb
#      ports:
#        - "3304:3306"
#      healthcheck:
#        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#        interval: 10s
#        timeout: 10s
#        retries: 10
#        start_period: 10s
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: cardsdb
#      networks:
#        - bank-microservice
#
#    loansdb:
#      image: mysql
#      container_name: loansdb
#      ports:
#        - "3303:3306"
#      healthcheck:
#        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#        interval: 10s
#        timeout: 10s
#        retries: 10
#        start_period: 10s
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: loansdb
#      networks:
#        - bank-microservice

    configserver:
      image: "hamedmiri72/configserver:s8"
      container_name: configserver-ms
      ports:
        - "8071:8071"
      healthcheck:
        test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice

    eurekaserver:
      image: "hamedmiri72/eurekaserver:s8"
      container_name: eurekaserver-ms
      ports:
        - "8070:8070"
      healthcheck:
        test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice
      depends_on:
        configserver:
          condition: service_healthy
      environment:
        SPRING_APPLICATION_NAME: "eurekaserver"
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"

    accounts:
      image: "hamedmiri72/accounts:s8"
      container_name: accounts-ms
      ports:
        - "8080:8080"

      depends_on:
        configserver:
          condition: service_healthy
        eurekaserver:
          condition: service_healthy
#        accountsdb:
#          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
        SPRING_PROFILES_ACTIVE: default
        SPRING_APPLICATION_NAME: "accounts"
#        SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3305/accountsdb"


    cards:
      image: "hamedmiri72/cards:s8"
      container_name: cards-ms
      ports:
        - "9000:9000"
      depends_on:
        configserver:
          condition: service_healthy
        eurekaserver:
          condition: service_healthy
#        cardsdb:
#          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
        SPRING_PROFILES_ACTIVE: default
        SPRING_APPLICATION_NAME: "cards"
#        SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3305/cardsdb"

    loans:
      image: "hamedmiri72/loans:s8"
      container_name: loans-ms
      ports:
        - "8090:8090"
      depends_on:
        configserver:
          condition: service_healthy
        eurekaserver:
          condition: service_healthy
#        loansdb:
#          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
        SPRING_PROFILES_ACTIVE: default
        SPRING_APPLICATION_NAME: "loans"
#        SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3305/loansdb"

    loans1:
      image: "hamedmiri72/loans:s8"
      container_name: loans-ms1
      ports:
        - "8091:8090"
      depends_on:
        configserver:
          condition: service_healthy
        eurekaserver:
          condition: service_healthy
      #        loansdb:
      #          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - bank-microservice
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
        SPRING_PROFILES_ACTIVE: default
        SPRING_APPLICATION_NAME: "loans"
  #        SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3305/loansdb"





networks:
  bank-microservice:
    driver: bridge


