
build:
  version: "3.0"


cards:
  message: "Welcome to cards microservice local APIs"
  contactDetails:
    name: "Hamed Miri"
    email: "hamedmiri72@gmailcom"
  onCallSupport:
    - (735) 584-8222
    - (735) 584-8223
