
build:
  version: "2.0"

loans:
  message: "Welcome to loans related production APIs"
  contactDetails:
    name: "Hamed Miri- Production lead"
    email: "hamedmiri72@gmailcom"
  onCallSupport:
    - (735) 584-8222
    - (735) 584-8223