

build:
  version: "1.0"

loans:
  message: "Welcome to loans related QA APIs"
  contactDetails:
    name: "Hamed Miri - QA lead"
    email: "hamedmiri72@gmailcom"
  onCallSupport:
    - (735) 584-8222
    - (735) 584-8223